from tkinter import*
from tkinter import ttk

class Resistor:
    def __init__(self, root):
        self.root = root
        self.root.title("Resistor Colour Code Calculator")
        self.root.geometry("1352x652+0+0")
        self.root.configure(background = "powder blue")

        mainFrame = Frame(self.root)
        mainFrame.grid()
        
        TitleFrame = Frame(mainFrame, bd = 10, width = 1350, padx = 20, relief = RIDGE)
        TitleFrame.grid(row = 0, column = 0)
        self.lblTitle = Label(TitleFrame, font = ('arial', 50, 'bold'), text = "Resistor Colour Code Calculator", padx = 100)
        self.lblTitle.grid()
        ResistorFrame = Frame(mainFrame, bd = 10, width = 1350, padx = 20, relief = RIDGE)
        ResistorFrame.grid(row = 1, column = 0) 

        self.lblTitle = Label(ResistorFrame, font = ('arial', 13, 'bold'), text = "1st Band")
        self.lblTitle.grid(row = 0, column = 0)
        self.lblTitle = Label(ResistorFrame, font = ('arial', 13, 'bold'), text = "2nd Band")
        self.lblTitle.grid(row = 0, column = 1)
        self.lblTitle = Label(ResistorFrame, font = ('arial', 13, 'bold'), text = "Multiplier")
        self.lblTitle.grid(row = 0, column = 2)
        self.lblTitle = Label(ResistorFrame, font = ('arial', 13, 'bold'), text = "Tolerance")
        self.lblTitle.grid(row = 0, column = 3)
        
        self.bkCBand1 = Button(ResistorFrame, width=13, font = ('arial', 14, 'bold'), text = 'black', fg = 'white', bg ='black')
        self.bkCBand1.grid(row = 1, column = 0)
        self.bkCBand2 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = '0', fg = 'white', bg = 'black')
        self.bkCBand2.grid (row = 1, column = 1)
        self.bkCBand3 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = '1', fg = 'white', bg = 'black')
        self.bkCBand3.grid (row = 1, column = 2)
        self.bkCBand4 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), fg = 'white', bg = 'black')
        self.bkCBand4.grid (row = 1, column = 3)
        
        self.brown1 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = 'Brown', fg = 'black', bg = 'brown')
        self.brown1.grid(row = 2, column = 0)
        self.brown2 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = '1', fg = 'white', bg = 'brown')
        self.brown2.grid(row = 2, column = 1)
        self.brown3 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = '10', fg = 'white', bg = 'brown')
        self.brown3.grid(row = 2, column = 2)
        self.brown4 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), fg = 'white', bg = 'brown')
        self.brown4.grid(row = 2, column = 3)

        self.red1 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = 'Red', fg = 'black', bg = 'red')
        self.red1.grid(row = 3, column = 0)
        self.red2 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = '2', fg = 'white', bg = 'red')
        self.red2.grid(row = 3, column = 1)
        self.red3 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = '100', fg = 'white', bg = 'red')
        self.red3.grid(row = 3, column = 2)
        self.red4 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), fg = 'white', bg = 'red')
        self.red4.grid(row = 3, column = 3)

        self.orange1 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = 'Orange', fg = 'black', bg = 'orange')
        self.orange1.grid(row = 4, column = 0)
        self.orange2 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = '3', fg = 'white', bg = 'orange')
        self.orange2.grid(row = 4, column = 1)
        self.orange3 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = '1000', fg = 'white', bg = 'orange')
        self.orange3.grid(row = 4, column = 2)
        self.orange4 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), fg = 'white', bg = 'orange')
        self.orange4.grid(row = 4, column = 3)

        self.yellow1 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = 'Yellow', fg = 'black', bg = 'yellow')
        self.yellow1.grid(row = 5, column = 0)
        self.yellow2 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = '4', fg = 'white', bg ='yellow')
        self.yellow2.grid(row = 5, column = 1)
        self.yellow3 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = '10000', fg = 'white', bg = 'yellow')
        self.yellow3.grid(row = 5, column = 2)
        self.yellow4 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), fg = 'white', bg = 'yellow')
        self.yellow4.grid(row = 5, column = 3)

        self.green1 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = 'Green', fg = 'black', bg = 'green')
        self.green1.grid(row = 6, column = 0)
        self.green2 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text= '5', fg = 'white', bg = 'green')
        self.green2.grid(row = 6, column = 1)
        self.green3 = Button(ResistorFrame, width = 13, font =('arial', 14, 'bold'), text = '100000', fg = 'white', bg = 'green')
        self.green3.grid(row = 6, column = 2)
        self.green4 = Button(ResistorFrame, width= 13, font =('arial', 14, 'bold'), fg = 'white', bg = 'green')
        self.green4.grid(row = 6, column = 3)

        self.blue1 = Button(ResistorFrame, width = 13, font =('arial', 14, 'bold'), text = 'Blue', fg = 'black', bg = 'blue')
        self.blue1.grid(row = 7, column = 0)
        self.blue2 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = '6', fg = 'white', bg = 'blue')
        self.blue2.grid(row = 7, column = 1)
        self.blue3 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = '1000000', fg = 'white', bg = 'blue')
        self.blue3.grid(row = 7, column = 2)
        self.blue4 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), fg = 'white', bg = 'blue')
        self.blue4.grid(row = 7, column = 3)

        self.violet1 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = 'Violet', fg = 'black', bg = 'violet')
        self.violet1.grid(row = 8, column = 0)
        self.violet2 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = '7', fg = 'white', bg = 'violet')
        self.violet2.grid(row = 8, column = 1)
        self.violet3 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = '10000000', fg = 'white', bg = 'violet')
        self.violet3.grid(row = 8, column = 2)
        self.violet4 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), fg = 'white', bg = 'violet')
        self.violet4.grid(row = 8, column = 3)

        self.gray1 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = 'Gray', fg = 'black', bg = 'gray')
        self.gray1.grid(row = 9, column = 0)
        self.gray2 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = '8', fg = 'white', bg = 'gray')
        self.gray2.grid(row = 9, column = 1)
        self.gray3 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = '100000000', fg = 'white', bg = 'gray')
        self.gray3.grid(row = 9, column = 2)
        self.gray4 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), fg = 'white', bg = 'gray')
        self.gray4.grid(row = 9, column = 3)

        self.white1 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = 'White', fg = 'black', bg = 'white')
        self.white1.grid(row = 10, column = 0)
        self.white2 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = '9', fg = 'black', bg = 'white')
        self.white2.grid(row = 10, column = 1)
        self.white3 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = '1000000000', fg = 'black', bg = 'white')
        self.white3.grid(row = 10, column = 2)
        self.white4 = Button(ResistorFrame, width= 13, font = ('arial', 14, 'bold'), fg = 'white', bg = 'white')
        self.white4.grid(row=10, column=3)

        self.Goldl = Button(ResistorFrame, width= 13, font = ('arial', 14, 'bold'), text = 'Gold', fg = 'black', bg = 'Gold') 
        self.Goldl.grid(row = 11, column = 0)
        self.Gold2 = Button(ResistorFrame, width= 13, font= ('arial', 14, 'bold'), text= '', fg = 'black', bg = 'Gold') 
        self.Gold2.grid(row = 11, column = 1)
        self.Gold3 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = '0.1', fg = 'black', bg = 'Gold') 
        self.Gold3.grid(row = 11, column = 2)
        self.Gold4 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = '5%', fg = 'black', bg = 'Gold') 
        self.Gold4.grid(row = 11, column = 3)

        self.Silverl = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = 'Silver', fg = 'black', bg = 'Silver')
        self.Silverl.grid(row = 12, column = 0)
        self.Silver2 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = '', fg = 'black', bg = 'Silver') 
        self.Silver2.grid(row = 12, column = 1)
        self.Silver3 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), fg = 'black', bg = 'silver') 
        self.Silver3.grid(row = 12, column = 2)
        self.Silver4 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = '10%', fg = 'black', bg = 'Silver') 
        self.Silver4.grid(row = 12, column = 3)
        
        self.Nonel = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = 'None', fg = 'black', bg = 'white') 
        self.Nonel.grid(row = 13, column = 0)
        self.None2 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = '', fg = 'black', bg = 'white') 
        self.None2.grid(row = 13, column = 1)
        self.None3 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), fg = 'black', bg = 'white') 
        self.None3.grid(row = 13, column = 2)
        self.None4 = Button(ResistorFrame, width = 13, font = ('arial', 14, 'bold'), text = '20%', fg = 'black', bg = 'white')
        self.None4.grid(row = 13, column = 3)
    

if __name__=='__main__':
    root = Tk()
    application = Resistor(root)
    root.mainloop()